FROM datajoint/djbase:py3.9-debian-fcd8909

USER anaconda:anaconda

COPY ./workflow-calcium-imaging/docker/apt_requirements.txt /tmp/
RUN /entrypoint.sh echo "Installed dependencies."

# Install Caiman
RUN git clone --branch master https://github.com/vathes/CaImAn 
WORKDIR /main/CaImAn
RUN conda install -n base -c conda-forge -y mamba
RUN /bin/bash -c 'mamba env update --n base --file environment.yml' 
# Suite2p complains if np.__version__ != 1.21
RUN pip install numpy==1.21
RUN pip install .

WORKDIR /main

RUN mkdir /main/element-lab \
          /main/element-animal \
          /main/element-session \
          /main/element-array-ephys \
          /main/workflow-calcium-imaging

# Copy user's local fork of elements and workflow
COPY --chown=anaconda:anaconda ./element-lab /main/element-lab
COPY --chown=anaconda:anaconda ./element-animal /main/element-animal
COPY --chown=anaconda:anaconda ./element-session /main/element-session
COPY --chown=anaconda:anaconda ./element-interface /main/element-interface
COPY --chown=anaconda:anaconda ./element-calcium-imaging /main/element-calcium-imaging
COPY --chown=anaconda:anaconda ./workflow-calcium-imaging /main/workflow-calcium-imaging

# Install packages
RUN pip install -e /main/element-lab
RUN pip install -e /main/element-animal
RUN pip install -e /main/element-session
RUN pip install -e /main/element-interface[scanreader,sbxreader,image_converter,suite2p]
RUN pip install -e /main/element-calcium-imaging
RUN pip install -e /main/workflow-calcium-imaging
RUN pip install -r /main/workflow-calcium-imaging/requirements_test.txt

WORKDIR /main/workflow-calcium-imaging

ENTRYPOINT ["tail", "-f", "/dev/null"]